# Site settings
title: CEMS.UL
email: theme@viennalabs.com
description: > # this means to ignore newlines until "baseurl:"
 Creative is a one page Bootstrap theme for creatives, small businesses, and other multipurpose uses.
 The theme includes a number of rich features and plugins that you can use as a great boilerplate for your next Jekyll project!
# Your name to show in the footer
author: Carlos Florentino

# Navegador
navbar-links:
  Aulas T/P :
    - Horário: "horarios"
    - Exercícios e Resumos: "exercicios"
    - Programa e Bibliografia: "programa"
  Recursos:
    - Vídeos: "https://www.youtube.com/c/Matem%C3%A1ticaDiscretaFCUL"
    - Outras Ligações: "ligacoes"
  Avaliação  :
    - Regras de Avaliação: "avaliacao"
    - Testes e Exames: "testes"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: volnyio
github_username:  volny

# Build settings
markdown: kramdown
